export default {
  THEME_CHANGE: 'THEME_CHANGE', //主题修改
  THEME_INIT: 'THEME_INIT', //主题初始化
  POPULAR_REFRESH: 'POPULAR_REFRESH', //列表下拉刷新时触发action
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL', //列表数据刷新失败
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS', //列表数据加载成功
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS', //上拉加载更多成功
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL', //上拉加载更多失败

  TRENDING_REFRESH: 'TRENDING_REFRESH', //列表下拉刷新时触发action
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL', //列表数据刷新失败
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS', //列表数据加载成功
  TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS', //上拉加载更多成功
  TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL', //上拉加载更多失败
};
