export default {
  THEME_CHANGE: 'THEME_CHANGE', //主题修改
  THEME_INIT: 'THEME_INIT', //主题初始化
  SHOW_THEME_VIEW: 'SHOW_THEME_VIEW', //展示自定义主题的dialog
  POPULAR_REFRESH: 'POPULAR_REFRESH', //列表下拉刷新时触发action
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL', //列表数据刷新失败
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS', //列表数据加载成功
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS', //上拉加载更多成功
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL', //上拉加载更多失败
  FLUSH_POPULAR_FAVORITE: 'FLUSH_POPULAR_FAVORITE',

  TRENDING_FLUSH_FAVORITE: 'TRENDING_FLUSH_FAVORITE',
  TRENDING_REFRESH: 'TRENDING_REFRESH', //列表下拉刷新时触发action
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL', //列表数据刷新失败
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS', //列表数据加载成功
  TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS', //上拉加载更多成功
  TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL', //上拉加载更多失败

  FAVORITE_LOAD_DATA: 'FAVORITE_LOAD_DATA',
  FAVORITE_LOAD_SUCCESS: 'FAVORITE_LOAD_SUCCESS',
  FAVORITE_LOAD_FAIL: 'FAVORITE_LOAD_FAIL',

  LANGUAGE_LOAD_SUCCESS: 'LANGUAGE_LOAD_SUCCESS',

  //搜索
  SEARCH_LOAD_MORE_SUCCESS: 'SEARCH_LOAD_MORE_SUCCESS',
  SEARCH_LOAD_MORE_FAIL: 'SEARCH_LOAD_MORE_FAIL',
  SEARCH_REFRESH: 'SEARCH_REFRESH',
  SEARCH_CANCEL: 'SEARCH_CANCEL',
  SEARCH_FAIL: 'SEARCH_FAIL',
  SEARCH_REFRESH_SUCCESS: 'SEARCH_REFRESH_SUCCESS',
};
